export const ActionTypes = {
  SET_EMPLOYEES: "SET_EMPLOYEES",
  SELECTED_EMPLOYEES: "SELECTED_EMPLOYEES",
  EMPLOYEE_BANK_DETAILS:"EMPLOYEE_BANK_DETAILS",
  EMPLOYEE_BOND:"EMPLOYEE_BOND",
  EMPLOYEE_SALARY:"EMPLOYEE_SALARY",
  REMOVESELECTED_EMPLOYEES: " REMOVESELECTED_EMPLOYEES",
}
